
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:Admin}

  jpa:
#    database: postgresql
#    database: pinceladas_belleza
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
#        default_schema: pinceladas_belleza
        default_schema: pinceladasdb
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update

jwt:
  secret: ${JWT_SECRET:rGFv2rHb8nQxTzLDN4UwPZoVbHzLkq3JD9gTMBYMGzQ=}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION:604800000}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

server:
  port: ${PORT:8080}
