
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=pinceladas_belleza
#    username: postgres
#    password: Admin
    url: jdbc:postgresql://ep-spring-dew-ahgmfoau-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_OK1iPykwZL8D

  jpa:
#    database: postgresql
#    database: pinceladas_belleza
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        default_schema: pinceladas_belleza
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none

jwt:
  secret: rGFv2rHb8nQxTzLDN4UwPZoVbHzLkq3JD9gTMBYMGzQ=
  expiration: 86400000
  refresh:
    expiration: 604800000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
