spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://biazz3hs24qqgnzjyikg-postgresql.services.clever-cloud.com:5432/biazz3hs24qqgnzjyikg?UseSSL=true&serverTimezone=UTC
#    username: ut0hpzqvekhwmlzyllzn
#    password: 99GPtyIQi7lQ5tt8WQv09qbwnGNAu2
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

    hikari:
      pool-name: HikariPool
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
      leak-detection-threshold: 20000

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: pinceladasdb
        hbm2ddl:
          auto: none

jwt:
  secret: rGFv2rHb8nQxTzLDN4UwPZoVbHzLkq3JD9gTMBYMGzQ=
  expiration: 86400000
  refresh:
    expiration: 604800000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

server:
  port: ${PORT:8080}

graphiql:
  enabled: true
  path: /graphiql
  endpoint: /graphql
